### PR TITLE
Added script to list plates for a screen

### PR DESCRIPTION
**Pull request by dpwrussell**

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
list_screen_plates.py did not work: 

```
jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_screen_plates.py 151
Traceback (most recent call last):
  File "./list_screen_plates.py", line 28, in <module>
    if not args.nonames:
AttributeError: 'Namespace' object has no attribute 'nonames'

**Comment by dpwrussell** [comment]
That error is because I hadn't added `--nonames` to that script. I have now properly added it.

**Comment by ghost** [comment]
Worked perfectly. Thanks.

```
jc168@clarinet002-071:~/Checkout/OMERO_scripts$ ./list_screen_plates.py 501
Screen Name, Plate Name, Plate ID
_rendered_Opera_Ralph_Neumuller, 112B94, 373
_rendered_Opera_Ralph_Neumuller, 113B44, 374
_rendered_Opera_Ralph_Neumuller, 113B45, 375
_rendered_Opera_Ralph_Neumuller, 113B88, 376
_rendered_Opera_Ralph_Neumuller, 113B89, 377
_rendered_Opera_Ralph_Neumuller, 113B90, 378
_rendered_Opera_Ralph_Neumuller, 114B46, 379
_rendered_Opera_Ralph_Neumuller, 114B47, 380
_rendered_Opera_Ralph_Neumuller, 114B84, 381
_rendered_Opera_Ralph_Neumuller, 115B46, 382
_rendered_Opera_Ralph_Neumuller, 115B47, 383
_rendered_Opera_Ralph_Neumuller, 116B46, 384
_rendered_Opera_Ralph_Neumuller, 116B47_final, 385
_rendered_Opera_Ralph_Neumuller, 117B45, 386
_rendered_Opera_Ralph_Neumuller, 117B46, 387
_rendered_Opera_Ralph_Neumuller, 118B45, 388
_rendered_Opera_Ralph_Neumuller, 118B46, 389
_rendered_Opera_Ralph_Neumuller, 118B96, 390
_rendered_Opera_Ralph_Neumuller, 119B47, 391
_rendered_Opera_Ralph_Neumuller, 119B48, 392
```

**Comment by ghost** [comment]
`--nonames` works too: 

```
jc168@clarinet002-071:~/Checkout/OMERO_scripts$ ./list_screen_plates.py --nonames 501
Plate ID
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
```

**Comment by ghost** [comment]
To use the --nonames option as a way to create a foreach loop it would be nice to omit the first line with "Plate ID".

**Comment by dpwrussell** [comment]
@jaycopeland #14 for your suggestion, it should be a separate option.

**Pull request merged**
