### PR TITLE
Remove field restriction and order results on list_screen_images

### PR DESCRIPTION
**Pull request by dpwrussell**
Removed restriction of only querying field 0 in list_screen_images and added fields to output. Also correctly ordered results on list_screen_images

### CODE REVIEW

**Comment by ghost** [comment]
Once the conflict is resolved you can merge.

**Comment by ghost** [comment]
The output of list_screen_images is different. I don't really understand what this pr is trying to do. The output looks like this: 
```
jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_screen_images.py 103
['Jerry Lin Test Screens', 'JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C1', 16385L]
['Jerry Lin Test Screens', 'JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C2', 16629L]
['Jerry Lin Test Screens', 'JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C3', 16413L]
['Jerry Lin Test Screens', 'JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C4', 16683L]
['Jerry Lin Test Screens', 'JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C5', 16422L]
['Jerry Lin Test Screens', 'JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C6', 16737L]

**Comment by dpwrussell** [comment]
Before this PR, only the 0th `field` was included. This adds all fields and a column to indicate that.

The reason the output was different is that this PR predates the standardized output. I have rebased it on the now merged #13 so it matches the other scripts.

**Comment by ghost** [comment]
Tested. Works fine.

**Pull request merged**
