### PR TITLE
list_plate_images script

### PR DESCRIPTION
**Pull request by dpwrussell**
Gets a list of image IDs for a given plate and also outputs the corresponding plate and plate ID.

### CODE REVIEW

**Comment by dpwrussell** [comment]
@jaycopeland I based the returned data on your script, but tweaked it a little bit to fit better with list_screen_images, but there is a little inconsistency.
- Should list_plate_images only query a single field like list_screen_images?
- Should list_plate_images return the information about the well like list_screen_images does?

Is this difference desirable or should they be more homogenous?

**Comment by ghost** [comment]
We also want to see well names.

**Comment by dpwrussell** [comment]
@jaycopeland Well names now displayed

**Comment by ghost** [comment]
The format include square brackets and quotes: 
```
jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_plate_images.py 153
['JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C1', 16385L]
['JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C2', 16629L]
['JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C3', 16413L]
['JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C4', 16683L]
['JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C5', 16422L]
['JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce', 153L, 0L, 'C6', 16737L]...

It would be better if the format were the same as the pr/13 with the -n option available.

**Comment by ghost** [comment]
There also should be a header row.

**Comment by dpwrussell** [comment]
Again, this predated the new format as the PR has been around for so long. Updated with new format.

**Comment by ghost** [comment]
test checks out. Looks ready to merge.: 

```
jc168@clarinet002-070:~/Checkout/OMERO_scripts$ ./list_plate_images.py 601
Plate Name, Plate ID, Field, Well, Image ID
101B115, 601, 0, A1, 437601
101B115, 601, 0, A2, 438504
101B115, 601, 0, A3, 438413
101B115, 601, 0, A4, 437763
101B115, 601, 0, A5, 439176
101B115, 601, 0, A6, 438819
101B115, 601, 0, A7, 437693
101B115, 601, 0, A8, 437819
101B115, 601, 0, A9, 439533
101B115, 601, 0, A10, 438756
101B115, 601, 0, A11, 437826
101B115, 601, 0, A12, 437903
101B115, 601, 0, A13, 439127
101B115, 601, 0, A14, 439491
101B115, 601, 0, A15, 438539
101B115, 601, 0, A16, 438392
101B115, 601, 0, A17, 439330
101B115, 601, 0, A18, 439827
101B115, 601, 0, A19, 439211
[clipped]
```

**Pull request merged**
