### PR TITLE
list_all_projects__with_datasets script

### PR DESCRIPTION
**Pull request by dpwrussell**
Script to list all projects visible to the user with all the child datasets of those. Does not show orphaned datasets.

Printed output is formatted as a tree. CSV output is flat rows.

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
I am not sure how this is supposed to work. Here's the result I got: 
```
jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_project_datasets.py 101
usage: list_project_datasets.py [-h] [-q | -p] [-f file]
list_project_datasets.py: error: unrecognized arguments: 101

**Comment by dpwrussell** [comment]
This predates the standard format implemented in some other scripts.

I will output in a non-tree based format the same as the other scripts.

@jaycopeland Do you really want the owners of the `projects|datasets|images` in these results? That is a little different to the other scripts so if that data is not needed, I will make it consistent and remove it.

**Comment by dpwrussell** [comment]
I am also going to change the name as it is confusing as this naming convention for our other scripts suggests listing all the datasets for this project, whereas this one lists all projects (with datasets) that a user can access.

This may be the reason that the owners are important, so it is fine if those should be kept.

**Comment by ghost** [comment]
Test worked. Ready to merge: 

```
jc168@clarinet002-070:~/Checkout/OMERO_scripts$ ./list_all_projects_with_datasets.py
Project Name, Project ID, Project Owner, Dataset Name, Dataset ID, Dataset Owner
testing, 1, root, logos, 1, root
Test, 551, rp197, test dataset, 701, rp197
Demos, 102, jc168, Jpegs of microscope room, 102, jc168
Demos, 102, jc168, Jerry's DV images, 103, jc168
Demos, 102, jc168, several jpgs, 104, jc168
Test, 551, rp197, test dataset 2, 751, rp197
testing, 201, cdarwin, test dataset, 201, cdarwin
Frank Lab, 252, gg113, Wholemount cornea from NFR1 stained with ABCB5, 252, gg113
Jerrold Turner Lab Testing, 101, jc168, 5.2.2 test, 302, jc168
my first OMERO project, 301, mw226, 2016-03-16 DCK, 303, mw226
my first OMERO project, 301, mw226, nd2, 304, mw226
Mahmoud testing, 152, jc168, 5.2.2 test, 305, jc168
OMX Reconstruction Scoring, 302, tjl10, SIRreconTEST, 306, tjl10
Temp, 652, he19, Temp, 802, he19
Jerry InCell Test, 303, jc168, Jerry-20160601-Slidescan_468P3_1, 309, jc168
Station 8 Flatfield, 753, ak434, St 8 40x PF, 862, ak434
Station 8 Flatfield, 753, ak434, St 8 60x PA, 863, ak434
Station 8 Flatfield, 753, ak434, St 8 100x PA, 864, ak434
Clonal cell evaluation, 356, wcs5, 20161018 3T3 IN+ sensor clones, 1053, wcs5
Calcium and Inversin, 305, wcs5, 20161019 Andor NP-EGTA 3T3 wt ko inv+, 1054, wcs5
Clonal cell evaluation, 356, wcs5, 20161020 3T3 IN+ sensor clones, 1055, wcs5
Clonal cell evaluation, 356, wcs5, 20160924 3T3 INV CRISPR IF Nek8, 1056, wcs5
Clonal cell evaluation, 356, wcs5, 20160925 Nek8 titration INV+, 1057, wcs5
Clonal cell evaluation, 356, wcs5, 20160926 INV IF, 1058, wcs5
Clonal cell evaluation, 356, wcs5, 20160926 INV KO INV+ sensor lines, 1059, wcs5
Clonal cell evaluation, 356, wcs5, 20160928 INV sensor clones, 1060, wcs5
Clonal cell evaluation, 356, wcs5, 20161003 3T3 INV sensor clones, 1061, wcs5
Clonal cell evaluation, 356, wcs5, 20161005 3T3 INV sensor clones, 1062, wcs5
Clonal cell evaluation, 356, wcs5, 20161007 CRISPR sensor clones, 1063, wcs5
Clonal cell evaluation, 356, wcs5, 20161007 IF 40X 3T3 WT NEK8 csap, 1064, wcs5
Calcium and Inversin, 305, wcs5, 20160918 Andor 3T3 WT GG3A1 NP-EGTA, 1068, wcs5
Clonal cell evaluation, 356, wcs5, 20160911 3T3 IF CSAP antibodies, 1069, wcs5
Clonal cell evaluation, 356, wcs5, 20160918 3T3 INV CRISPR IF Nek8 GT335 polyE, 1070, wcs5
IDACforJerryLSP_StitchingAndAlignment, 653, he19, FlatfieldCorrectionAndStichTest, 803, he19
IDACforJerryLSP_StitchingAndAlignment, 653, he19, FFC_Stich_SplineReg, 851, he19
IDACforJerryLSP_StitchingAndAlignment, 653, he19, FFC_Stitch_TranslationReg, 853, he19
IDACforJerryLSP_StitchingAndAlignment, 653, he19, Stitch_NoFFC, 854, he19
test, 851, ld48, Feng Di, 1156, ld48
Station 2 Flatfield (Confocal), 902, ak434, 20x_PA_0.75_488, 1208, ak434
Station 2 Flatfield (Confocal), 902, ak434, 40x_PF_1.3_488, 1209, ak434
Station 2 Flatfield (Confocal), 902, ak434, 100x_PA_1.4_488, 1211, ak434
Calcium and Inversin, 305, wcs5, 20161107 Andor ATP INV+, 1255, wcs5
Emily, 353, me129, BGS 25 ,1, 406, me129
Clonal cell evaluation, 356, wcs5, 20161029 IF 3T3 polyE flag, 1305, wcs5
ImageJ Testing, 351, jc168, from Mac, 402, jc168
Adam, 352, me129, AG150, 403, me129
Adam, 352, me129, aligned tifs, 404, me129
Mahmoud Testing, 354, jc168, Merged TIFFS, 405, jc168
Calcium and Inversin, 305, wcs5, 20160913 Andor NP-EGTA wt 3T3, 1067, wcs5
Calcium and Inversin, 305, wcs5, 20160911 Andor NP-EGTA wt3T3, 1066, wcs5
Calcium and Inversin, 305, wcs5, 20160609 Andor NP-EGTA, 311, wcs5
diSPIM, 307, wcs5, 20160423 diSPIM, 352, wcs5
Clonal cell evaluation, 356, wcs5, 20160617 ss clones, 310, wcs5
Clonal cell evaluation, 356, wcs5, 20160614 3T3 GG2C1 green background, 312, wcs5
Clonal cell evaluation, 356, wcs5, 20151220 clonal line characterization, 313, wcs5
Clonal cell evaluation, 356, wcs5, 20152021 clonal cell characterization, 314, wcs5
Clonal cell evaluation, 356, wcs5, 20152022 clonal cell characterization, 315, wcs5
Clonal cell evaluation, 356, wcs5, 20151209 clonal line tests, 316, wcs5
Clonal cell evaluation, 356, wcs5, 20160103clonal cell characterization, 317, wcs5
TMA Demo, 651, rp197, CFTR_150720, 805, rp197
Clonal cell evaluation, 356, wcs5, 20160807 3T3 CRISPR IF repeat, 655, wcs5
Calcium and Inversin, 305, wcs5, 20160721 Andor 3T3 NP-EGTA, 554, wcs5
Clonal cell evaluation, 356, wcs5, 20151114 3t3 5HT6-mCherry-GECO, 330, wcs5
incell test, 357, jc168, desktop random, 420, jc168
import tests, 358, jc168, McGill 40x, 421, jc168
import tests, 358, jc168, from desktop, 422, jc168
import tests, 358, jc168, Downloads, 451, jc168
Teaching, 401, jw42, Images for Teaching, 503, jw42
Teaching, 401, jw42, Fig1_ dirty vs clean lens, 553, jw42
Priah Collaboration, 451, tjl10, 20160720, 555, tjl10
Priah Collaboration, 451, tjl10, 20160714, 556, tjl10
Priah Collaboration, 451, tjl10, 20160712, 557, tjl10
Station 8 Flatfield, 753, ak434, St 8 10x SF, 858, ak434
Station 8 Flatfield, 753, ak434, St 8 10x PF, 859, ak434
Station 8 Flatfield, 753, ak434, St 8 20x PA, 861, ak434
IDACforJerryLSP_StitchingAndAlignment, 653, he19, FFC_Stitch, 852, he19
Dark Images, 702, ak434, Station 8 Dark Images, 855, ak434
Clonal cell evaluation, 356, wcs5, 20160819 3T3 INV CRISPR sensor IF, 658, wcs5
VSI Testing, 501, md267, Test Whole Slide Image, 663, md267
Calcium and Inversin, 305, wcs5, 20160219 laser zapping 3t3, 338, wcs5
Calcium and Inversin, 305, wcs5, 20160307 laser ablation, 339, wcs5
Calcium and Inversin, 305, wcs5, 20160329 IMCD membrane zapping, 343, wcs5
Calcium and Inversin, 305, wcs5, 20160408 IMCD ablation, 344, wcs5
Calcium and Inversin, 305, wcs5, 20160410 ablation, 345, wcs5
Calcium and Inversin, 305, wcs5, 20160626 Andor 3T3 clones, 415, wcs5
Calcium and Inversin, 305, wcs5, 20160704 Andor 3T3 clones NP-EGTA, 416, wcs5
Calcium and Inversin, 305, wcs5, 20160710 Andor 3T3 NP-EGTA, 551, wcs5
Calcium and Inversin, 305, wcs5, 20160418 Andor NP-EGTA, 552, wcs5
Calcium and Inversin, 305, wcs5, 20160626 Andor 3T3 clones, 603, wcs5
Calcium and Inversin, 305, wcs5, 20160827 Andor 3T3 wt NP-EGTA, 652, wcs5
Calcium and Inversin, 305, wcs5, 20160819 Andor 3T3 NP-EGTA, 659, wcs5
Calcium and Inversin, 305, wcs5, 20160819 Zeiss710, 660, wcs5
Calcium and Inversin, 305, wcs5, 20160823 Zeiss710, 661, wcs5
Calcium and Inversin, 305, wcs5, 20160825 Andor 3T3 NP-EGTA, 662, wcs5
Clonal cell evaluation, 356, wcs5, 20160115 3t3 clonal cells starvation test, 318, wcs5
Clonal cell evaluation, 356, wcs5, 20160118 3t3 clonal cells starvation test, 319, wcs5
Clonal cell evaluation, 356, wcs5, 20150623 llcpk1 tests, 321, wcs5
Clonal cell evaluation, 356, wcs5, 20150624 llcpk1 tests, 322, wcs5
Clonal cell evaluation, 356, wcs5, 20150731 llcpk1 5ht6-mCh-GECO ATP, 323, wcs5
Clonal cell evaluation, 356, wcs5, 20150807_transfection_test, 324, wcs5
Clonal cell evaluation, 356, wcs5, 20150811 3t3 5HT6 FG, 325, wcs5
Clonal cell evaluation, 356, wcs5, 20151006 stable cells tests, 326, wcs5
Calcium and Inversin, 305, wcs5, 20151012 ATP dil + ionom 3T3 + LLC-PK1, 327, wcs5
Calcium and Inversin, 305, wcs5, 20151013 ATP+Ionom 3T3 5HT6-GECO, 328, wcs5
Clonal cell evaluation, 356, wcs5, 20151016 reuse cells ATP + Ionom 3T3 5HT6-GECO, 329, wcs5
Clonal cell evaluation, 356, wcs5, 20151122 3T3 5HT6-mCh-GECO+GCaMP, 331, wcs5
Clonal cell evaluation, 356, wcs5, 20160622 3T3 hygro kill curve, 417, wcs5
Clonal cell evaluation, 356, wcs5, 20160729 3T3 INV CRISPR 6B5, 602, wcs5
Clonal cell evaluation, 356, wcs5, 20160827 3T3 IF Nek8 poly-E CSAP GT335, 651, wcs5
Clonal cell evaluation, 356, wcs5, 20160724 3T3 INV CRISPR INV+ lines, 653, wcs5
Clonal cell evaluation, 356, wcs5, 20160818 3T3 INV CRISPR 5HT6-mCh-G ATP, 656, wcs5
Clonal cell evaluation, 356, wcs5, 20160819 3T3 INV CRISPR IF, 657, wcs5
Clonal cell evaluation, 356, wcs5, 20160830 3T3 IF Nek8 poly-E CSAP GT335, 664, wcs5
Clonal cell evaluation, 356, wcs5, 20160902 3T3 IF fix block test poly-E CSAP, 665, wcs5
Clonal cell evaluation, 356, wcs5, 20160905 3T3 IF test CSAP GT335, 666, wcs5
Clonal cell evaluation, 356, wcs5, 20151209 cells on beads, 332, wcs5
Clonal cell evaluation, 356, wcs5, 20160120 3t3 on side, 333, wcs5
Clonal cell evaluation, 356, wcs5, 20160122 3t3 on side, 334, wcs5
Clonal cell evaluation, 356, wcs5, 20160127 3t3 2c1 side, 335, wcs5
Clonal cell evaluation, 356, wcs5, 20160129 3t3 GG2C1 on side, 336, wcs5
Clonal cell evaluation, 356, wcs5, 20160212 IMCD test, 337, wcs5
Clonal cell evaluation, 356, wcs5, 20160309 CRISPR, 340, wcs5
Clonal cell evaluation, 356, wcs5, 20160309 filter growth test, 341, wcs5
Clonal cell evaluation, 356, wcs5, 20160326 membranes, 342, wcs5
Clonal cell evaluation, 356, wcs5, 20160611 INV siRNA assessment, 346, wcs5
Clonal cell evaluation, 356, wcs5, 20160614 3T3 GG2C1 green background, 347, wcs5
Clonal cell evaluation, 356, wcs5, 20160617 IF, 348, wcs5
Clonal cell evaluation, 356, wcs5, 20160705 3T3 INV CRISPR clones, 407, wcs5
Clonal cell evaluation, 356, wcs5, 20160709 3T3 INV CRISPR clones, 408, wcs5
Clonal cell evaluation, 356, wcs5, 20160628 3T3 INV CRISPR clones, 409, wcs5
Clonal cell evaluation, 356, wcs5, 20160701 3T3 INV CRISPR clones, 410, wcs5
Clonal cell evaluation, 356, wcs5, 20160626 IMCD 2C6 5-mCh-G ss clones, 411, wcs5
Clonal cell evaluation, 356, wcs5, 20160627 IMCD 2C6 5-mCh-G ss clones, 412, wcs5
Clonal cell evaluation, 356, wcs5, 20160622 IMCD 2C6 5HT6-mCh-GECO clones, 413, wcs5
Clonal cell evaluation, 356, wcs5, 20160622 3T3 GG2C1 clones, 414, wcs5
Aziz, 751, jc168, Troubleshooting for Aziz, 901, jc168
Station 1 Flatfield, 754, ak434, 20x_PA_0.75, 902, ak434
Station 1 Flatfield, 754, ak434, 20x_PF_Multi_0.75, 903, ak434
Station 1 Flatfield, 754, ak434, 40x_PA_0.95, 904, ak434
Station 1 Flatfield, 754, ak434, 40x_PA_1.0, 905, ak434
Station 1 Flatfield, 754, ak434, 60x_PA_1.4, 906, ak434
Station 1 Flatfield, 754, ak434, 100x_PA_1.4, 907, ak434
Demos, 102, jc168, rc training, 908, jc168
Testing, 755, dt30, Testing, 912, dt30
LaVision, 756, dt30, Rose, 913, dt30
Dark Images, 702, ak434, Station 4 Dark Images, 951, ak434
Dark Images, 702, ak434, Station 10 Dark Images, 952, ak434
Dark Images, 702, ak434, Station 12 Dark Images, 953, ak434
Clonal cell evaluation, 356, wcs5, 20161015 3T3 INV CRISPR sensor clones, 1051, wcs5
Clonal cell evaluation, 356, wcs5, 20161018 3T3 IF wt 6A3 KO INV+ Nek8 Poly-E, 1052, wcs5
Calcium and Inversin, 305, wcs5, 20161023 Andor NP-EGTA 3T3 wt KO INV+, 1071, wcs5
Calcium and Inversin, 305, wcs5, 20161012Andor NP-EGTA 3T3 wt 6A3 INV+, 1072, wcs5
Graphics Card Tests, 801, dt30, LaVision, 1101, dt30
TMA Demo, 651, rp197, H&E, 1151, mmo12
Graphics Card Tests, 801, dt30, Wkst3, 1152, dt30
import tests, 358, jc168, IDAC, 1155, jc168
Calcium and Inversin, 305, wcs5, 20161110 Andor ATP 3T3 WT KO INV+, 1201, wcs5
Clonal cell evaluation, 356, wcs5, 20161024 3T3 IF wt 6A3 KO INV+ Nek8 Poly-E, 1202, wcs5
Calcium and Inversin, 305, wcs5, ASN movies, 1203, wcs5
Lattice, 901, tjl10, deskewed, 1204, tjl10
Station 2 Flatfield (Confocal), 902, ak434, 4x_PA_0.3_488, 1206, ak434
Station 2 Flatfield (Confocal), 902, ak434, 10x_PF__0.3_488, 1207, ak434
Station 2 Flatfield (Confocal), 902, ak434, 60x_PA_1.4_488, 1210, ak434
Hunter Elliot Testing, 852, jc168, converted to 16 bit using Fiji, 1158, jc168
Jerrold Turner Lab Testing, 101, jc168, Turner Lab Tests, 1251, jc168
Batch Test, 951, dt30, FijiDemonstration, 1252, dt30
Calcium and Inversin, 305, wcs5, 20161119 Andor NP-EGTA ATP 3T3, 1253, wcs5
Calcium and Inversin, 305, wcs5, 20161107 Andor ATP WT, 1254, wcs5
Calcium and Inversin, 305, wcs5, 20161107 Andor ATP KO, 1256, wcs5
Calcium and Inversin, 305, wcs5, 20161123 Andor ATP 3T3 INV+8E3, 1303, wcs5
Clonal cell evaluation, 356, wcs5, 20161121 IF 3T3 Gt335 testing, 1306, wcs5
Calcium and Inversin, 305, wcs5, 20161126 ATP WF 3T3 3A1 7F7 8E3 1C4, 1309, wcs5
Calcium and Inversin, 305, wcs5, 20161127 Andor ATP 3T3 8E3, 1310, wcs5
Clonal cell evaluation, 356, wcs5, 20161126 IF 3T3 3A1 7F7 8E3, 1311, wcs5
Station 12 Flatfield, 1001, ak434, 10x_PF_0.3_GFP, 1314, ak434
Station 12 Flatfield, 1001, ak434, 20x_PA_0.75_GFP, 1315, ak434
Station 12 Flatfield, 1001, ak434, 20x_PF_ELWD_0.45_GFP, 1316, ak434
Station 12 Flatfield, 1001, ak434, 40x_PA_0.95_GFP, 1317, ak434
TMA Demo, 651, rp197, NKCC1_150720 , 1258, mmo12
Dark Images, 702, ak434, Station 1 Dark Images, 1001, ak434
Station 12 Flatfield, 1001, ak434, 40x_PF_ELWD_0.6_GFP, 1318, ak434
Station 12 Flatfield, 1001, ak434, 60x_PA_1.4_GFP, 1319, ak434
Calcium and Inversin, 305, wcs5, 20161123 Andor ATP 3T3 KO7F7, 1301, wcs5
Calcium and Inversin, 305, wcs5, 20161123 Andor ATP 3T3 wtGG3A1, 1302, wcs5
Station 5 Flatfield, 1054, ak434, 10x_PF_0.3_GFP, 1353, ak434
Station 5 Flatfield, 1054, ak434, 20x_PA_0.75_GFP, 1354, ak434
Station 5 Flatfield, 1054, ak434, 20x_PF_ELWD_0.45_GFP, 1355, ak434
Station 5 Flatfield, 1054, ak434, 40x_PA_0.95_GFP, 1356, ak434
Station 5 Flatfield, 1054, ak434, 40x_PF_0.75_GFP, 1357, ak434
Station 5 Flatfield, 1054, ak434, 40x_PF_ELWD_0.6_GFP, 1358, ak434
JiuJiu, 1055, dt30, Jiujiu, 1360, dt30
LaVision, 756, dt30, Mary, 1361, dt30
Station 10 Flatfield, 1057, ak434, 20x_PF_0.75, 1363, ak434
Station 10 Flatfield, 1057, ak434, 20xPA_0.75, 1364, ak434
Station 10 Flatfield, 1057, ak434, 40x PF_0.75, 1365, ak434
Station 10 Flatfield, 1057, ak434, 40x_PF_1.3, 1366, ak434
Station 10 Flatfield, 1057, ak434, 60x_PA_1.4, 1367, ak434
Station 10 Flatfield, 1057, ak434, 100x_PA_1.45, 1368, ak434
Jerrold Turner Lab Testing, 101, jc168, 12-7 tests, 1402, jc168
Jerrold Turner Lab Testing, 101, jc168, 12-8, 1403, jc168
Aperio_test, 1101, jl503, H&E, 1452, jl503
Concept Demonstrations, 1102, tjl10, farnesyl_60x_confocal_2fps, 1453, tjl10
Jerrold Turner Lab Testing, 101, jc168, 12-9, 1454, jc168
import tests, 358, jc168, jstack test, 1455, jc168
test, 1103, bha6, test ds, 1456, bha6
Calcium and Inversin, 305, wcs5, 20161212 ATP multiple WT INV+, 1457, wcs5
deciliation, 1152, wcs5, 20161216 Deciliation INVS KO, 1502, wcs5
form demo project, 355, jc168, lskdjfl, 1505, jc168
Forms Demo Project, 1153, jc168, dlkfsl, 1507, jc168
Graphics Card Tests, 801, dt30, Wkst3 Updated, 1508, dt30
import tests, 358, jc168, tiled tiff, 1515, jc168
Jerrold Turner Lab Testing, 101, jc168, Dec 27, 1517, jc168
Jerrold Turner Lab Testing, 101, jc168, Dec 29, 1520, jc168
Clonal cell evaluation, 356, wcs5, 20161214 IF anks6 flag sensor clones, 1521, wcs5
Calcium and Inversin, 305, wcs5, 20161221 3T3 ATP wt polycl KO 7F7, 1522, wcs5
Calcium and Inversin, 305, wcs5, 20161219 3T3 wt 1C4 ATP, 1523, wcs5
import tests, 358, jc168, Jerry Lin Aperio Test Retry, 1526, jc168
Jerrold Turner Lab Testing, 101, jc168, Turner Jan 5, 1527, jc168
Calcium and Inversin, 305, wcs5, 20170106 Andor NP-EGTA, 1528, wcs5
Calcium and Inversin, 305, wcs5, 20170104 Andor ATP wt KO, 1530, wcs5
demo, 1154, jc168, blah, 1533, jc168
Import Tests After Firewall Reconfig, 1156, jc168, jrttest, 1535, jc168
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle06-GBM-Scan_20160726_100038_01x4x00221.rcpnl, 1540, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle02-GBM-Scan_20160720_104656_01x4x00221.rcpnl, 1536, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle03-GBM-Scan_20160721_095534_01x4x00221.rcpnl , 1537, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle04-GBM-Scan_20160722_131501_01x4x00221.rcpnl, 1538, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle01-GBM-Scan_20160719_104629_01x4x00238.rcpnl, 1534, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle07-GBM-Scan_20160727_102830_01x4x00221.rcpnl, 1541, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle09-GBM-Scan_20160729_122046_01x4x00221.rcpnl, 1543, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle10-GBM-Scan_20160801_113857_01x4x00221.rcpnl, 1544, jl503
Import Tests After Firewall Reconfig, 1156, jc168, EE H&E test 1, 1548, jc168
Dark Images, 702, ak434, Station 5 Dark Images, 1369, ak434
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle05-GBM-Scan_20160725_100025_01x4x00221.rcpnl, 1539, jl503
CycIF_FFPE_GBM_For_IDAC, 1155, jl503, Cycle08-GBM-Scan_20160728_112504_01x4x00221.rcpnl, 1542, jl503
Calcium and Inversin, 305, wcs5, 20170114 Andor NP_EGTA WTpolyclP KO7F7, 1549, wcs5
Clonal cell evaluation, 356, wcs5, 20170111 cell eval 6A3sens 6A3+sens WTpolyclP WTpolyclB, 1550, wcs5
Calcium and Inversin, 305, wcs5, 20170108 Andor NP-EGTA wt, 1529, wcs5
Calcium and Inversin, 305, wcs5, 20170116 Andor NP-EGTA 3T3 KO7F7 wtPolyclBl, 1551, wcs5
Import Tests After Firewall Reconfig, 1156, jc168, 1-17-2017 10:56, 1602, jc168
Import Tests After Firewall Reconfig, 1156, jc168, EE H&E 2, 1601, jc168
Jerrold Turner Lab Testing, 101, jc168, 2017-01-27, 1701, jc168
Foxd1GCE-Ezh2 Test, 1251, mtv8, 20160615-90i, 1702, mtv8
RP TEST, 1058, rp197, 170201test, 1703, rp197
NIC Test, 1301, jc168, Anne, 1751, jc168
Dark Images, 702, ak434, Station 9 Dark Images, 1752, ak434
Station 9 Flatfield, 1302, ak434, 10x_PF_0.3, 1753, ak434
Station 9 Flatfield, 1302, ak434, 20x_PA_0.75, 1754, ak434
Station 9 Flatfield, 1302, ak434, 20x_PF_0.45, 1755, ak434
Station 9 Flatfield, 1302, ak434, 40x_PA_0.95, 1756, ak434
Station 9 Flatfield, 1302, ak434, 10x_PF_0.3, 1757, ak434
Dark Images, 702, ak434, Station 15 Dark Images, 1758, ak434
LaVision, 756, dt30, Spatial Calibrations, 1759, dt30
TMA Final, 1305, rp197, SGLT1_161102, 1760, rp197
TMA Final, 1305, rp197, CFTR, 1761, mmo12
TMA Final, 1305, rp197, DRA, 1762, mmo12
TMA Final, 1305, rp197, NaKATPase, 1764, mmo12
TMA Final, 1305, rp197, NHE3, 1765, mmo12
TMA Final, 1305, rp197, NKCC1, 1766, mmo12
TRIPLET4, 1308, jl503, Cycle0, 1767, jl503
TRIPLET4, 1308, jl503, Cycle1, 1768, jl503
TRIPLET4, 1308, jl503, Cycle2, 1769, jl503
TRIPLET4, 1308, jl503, Cycle3, 1770, jl503
TRIPLET4, 1308, jl503, Cycle4, 1771, jl503
TRIPLET4, 1308, jl503, Cycle5, 1772, jl503
TRIPLET4, 1308, jl503, Cycle6, 1773, jl503
TRIPLET4, 1308, jl503, Cycle7, 1774, jl503
TRIPLET4, 1308, jl503, Cycle8, 1775, jl503
TRIPLET4, 1308, jl503, Cycle9, 1776, jl503
TRIPLET4, 1308, jl503, Cycle10, 1777, jl503
TRIPLET4, 1308, jl503, Cycle11, 1778, jl503
TMA Final, 1305, rp197, PEPT1, 1779, mmo12
LaVision, 756, dt30, Lai, 1780, dt30
LaVision, 756, dt30, Dan, 1781, dt30
Calcium and Inversin, 305, wcs5, 20170120 Andor NP-EGTA 7F7 wt, 1782, wcs5
Station 2 Dichroic Dust, 1310, ak434, St 2 Dichroic Dust, 1784, ak434
testing project, 1317, jc168, Pre-processed Images, 1785, jc168
test for this video, 1311, jc168, Downloads, 1787, jc168
import tests, 358, jc168, demo, 1788, jc168
Demo Project, 1312, jc168, Demo Dataset, 1789, jc168
A new project for demonstrating Insight, 1314, jc168, Random tif from my downloads, 1792, jc168
first import demonstration, 1315, jc168, My images, 1793, jc168
New Import Project for Demo, 1316, jc168, New Dataset for Demonstration, 1794, jc168
New Import Project for Demo, 1316, jc168, My images, 1795, jc168
Jerrold Turner Lab Testing, 101, jc168, preprocessing demo, 1805, jc168
Pituitary Cilia and Hormones, 1319, rr195, N12-194-A11, 1808, rr195
Pituitary Cilia and Hormones, 1319, rr195, N12-160-A19, 1809, rr195
Pituitary Cilia and Hormones, 1319, rr195, N16-200-A5, 1810, rr195
sticher testing, 1321, jc168, sticher test, 1811, jc168
Swathi, 1322, dt30, Mar 7 2017 - MDCK Tfr-TMR, 1813, dt30
Misc, 1323, rr195, Pituitary, 1814, rr195
PDL1 in ACP and PCP, 1324, rr195, PCP_67170, 1815, rr195
PDL1 in ACP and PCP, 1324, rr195, ACP_39322, 1816, rr195
testing, 601, kmh40, None, None, None
CART, 1351, rr195, None, None, None
OMERO TEST Aram, 151, me129, None, None, None
Santagata, 1320, jc168, None, None, None
Station 15 Flatfield, 1304, ak434, None, None, None
jc168@clarinet002-070:~/Checkout/OMERO_scripts$
```

**Pull request merged**
