### PR TITLE
List project images

### PR DESCRIPTION
**Pull request by dpwrussell**
Like the 'list screen images', but for a project.

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Works as expected. Should we add the -n option?

**Comment by dpwrussell** [comment]
`--nonames` added.

**Comment by ghost** [comment]
Looks good. Please merge. 

```
jc168@clarinet002-070:~/Checkout/OMERO_scripts$ ./list_project_images.py 102
Project Name, Dataset Name, Dataset ID, Image Name, Image ID
Demos, Jpegs of microscope room, 102, 7-color InsightSSI Combined Set.jpg, 111
Demos, Jpegs of microscope room, 102, Columbus screen capture.jpg, 112
Demos, Jpegs of microscope room, 102, Image.jpg, 113
Demos, Jpegs of microscope room, 102, IMG_0187.jpg, 114
Demos, Jpegs of microscope room, 102, IMG_0188.jpg, 115
Demos, Jpegs of microscope room, 102, IMG_0189.jpg, 116
Demos, Jpegs of microscope room, 102, IMG_1672.jpg, 117
Demos, Jerry's DV images, 103, Jerry-BJ5-PIP-20160217_01_R3D.dv, 179
Demos, several jpgs, 104, Image.jpg, 180
Demos, several jpgs, 104, IMG_0187.jpg, 181
Demos, several jpgs, 104, IMG_0188.jpg, 182
Demos, several jpgs, 104, IMG_0189.jpg, 183
Demos, several jpgs, 104, IMG_1672.jpg, 184
Demos, several jpgs, 104, IMG_1673.jpg, 185
Demos, several jpgs, 104, IMG_1674.jpg, 186
Demos, several jpgs, 104, IMG_1675.jpg, 187
Demos, several jpgs, 104, IMG_1676.jpg, 188
Demos, several jpgs, 104, Image.ome.tif, 16377
Demos, several jpgs, 104, IMG_0188.ome.tif, 16378
Demos, several jpgs, 104, Image.ome.tif, 16379
Demos, several jpgs, 104, IMG_0189.ome.tif, 16380
Demos, several jpgs, 104, IMG_0188.ome.tif, 16381
Demos, several jpgs, 104, SurfacePlot.ome.tif, 16382
Demos, several jpgs, 104, 12270104.jpg, 445992
Demos, rc training, 908, cellimages.tiff, 440705
Demos, rc training, 908, schoolbus.jpg, 440706
```

**Pull request merged**
