### PR TITLE
Added nonames option

### PR DESCRIPTION
**Pull request by dpwrussell**

### CODE REVIEW

**Comment by ghost** [comment]
OK, looks good.

**Comment by ghost** [comment]
The -n option does not work. For example, here's the output of first without it and then with it: 

```jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_screen_images.py 103
Screen Name, Plate Name, Plate Name, Plate ID, Well, Image ID
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C1, 16385
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F5, 16800
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D5, 16791
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F12, 16782
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D6, 16773
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F2, 16764
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D8, 16755
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D4, 16746
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C6, 16737
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E12, 16728
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F1, 16719
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E1, 16710
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C11, 16701
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C7, 16692
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C4, 16683
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F6, 16674
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C9, 16665
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F8, 16656
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D12, 16647
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F3, 16638
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C2, 16629
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F9, 16620
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E4, 16611
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E2, 16602
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D1, 16593
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D3, 16584
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F10, 16575
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E5, 16566
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E8, 16557
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E3, 16548
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C12, 16539
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E11, 16530
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D2, 16521
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F7, 16512
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E6, 16503
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C8, 16494
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D10, 16485
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D9, 16476
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C10, 16467
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D11, 16458
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E10, 16449
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, D7, 16440
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F11, 16431
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C5, 16422
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, C3, 16413
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E9, 16404
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, F4, 16395
Jerry Lin Test Screens, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 153, E7, 16386

jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_screen_images.py -n 103
Screen Name, Plate Name, Plate ID, Well, Image ID
Jerry Lin Test Screens, 153, 2, A16386
Jerry Lin Test Screens, 153, 5, E16801
Jerry Lin Test Screens, 153, 3, E16792
Jerry Lin Test Screens, 153, 5, L16783
Jerry Lin Test Screens, 153, 3, F16774
Jerry Lin Test Screens, 153, 5, B16765
Jerry Lin Test Screens, 153, 3, H16756
Jerry Lin Test Screens, 153, 3, D16747
Jerry Lin Test Screens, 153, 2, F16738
Jerry Lin Test Screens, 153, 4, L16729
Jerry Lin Test Screens, 153, 5, A16720
Jerry Lin Test Screens, 153, 4, A16711
Jerry Lin Test Screens, 153, 2, K16702
Jerry Lin Test Screens, 153, 2, G16693
Jerry Lin Test Screens, 153, 2, D16684
Jerry Lin Test Screens, 153, 5, F16675
Jerry Lin Test Screens, 153, 2, I16666
Jerry Lin Test Screens, 153, 5, H16657
Jerry Lin Test Screens, 153, 3, L16648
Jerry Lin Test Screens, 153, 5, C16639
Jerry Lin Test Screens, 153, 2, B16630
Jerry Lin Test Screens, 153, 5, I16621
Jerry Lin Test Screens, 153, 4, D16612
Jerry Lin Test Screens, 153, 4, B16603
Jerry Lin Test Screens, 153, 3, A16594
Jerry Lin Test Screens, 153, 3, C16585
Jerry Lin Test Screens, 153, 5, J16576
Jerry Lin Test Screens, 153, 4, E16567
Jerry Lin Test Screens, 153, 4, H16558
Jerry Lin Test Screens, 153, 4, C16549
Jerry Lin Test Screens, 153, 2, L16540
Jerry Lin Test Screens, 153, 4, K16531
Jerry Lin Test Screens, 153, 3, B16522
Jerry Lin Test Screens, 153, 5, G16513
Jerry Lin Test Screens, 153, 4, F16504
Jerry Lin Test Screens, 153, 2, H16495
Jerry Lin Test Screens, 153, 3, J16486
Jerry Lin Test Screens, 153, 3, I16477
Jerry Lin Test Screens, 153, 2, J16468
Jerry Lin Test Screens, 153, 3, K16459
Jerry Lin Test Screens, 153, 4, J16450
Jerry Lin Test Screens, 153, 3, G16441
Jerry Lin Test Screens, 153, 5, K16432
Jerry Lin Test Screens, 153, 2, E16423
Jerry Lin Test Screens, 153, 2, C16414
Jerry Lin Test Screens, 153, 4, I16405
Jerry Lin Test Screens, 153, 5, D16396
Jerry Lin Test Screens, 153, 4, G16387

**Comment by dpwrussell** [comment]
I have pushed a fix for that.

**Comment by ghost** [comment]
The Well and Image ID column are still showing the wrong information. Also without the --nonames option the script causes an error. I have no idea what that alphanumeric is. The number portion does not correspond to real Image IDs.

```jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_screen_images.py 152 | head
Screen Name, Plate Name, Plate Name, Plate ID, Well, Image ID
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, F12, 18968
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, E9, 18959
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, D8, 18950
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, D7, 18941
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, D5, 18932
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, D11, 18923
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, E6, 18914
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, D1, 18905
INCell Tests, JY-20160517-IMR90_IMR90-HRas-DiffAbs_1.xdce, 154, C4, 18896
Traceback (most recent call last):
  File "./list_screen_images.py", line 67, in <module>
    print ', '.join([str(item) for item in row])
IOError: [Errno 32] Broken pipe
jc168@clarinet001-054:~/Checkout/OMERO_scripts$ ./list_screen_images.py --nonames 152 | head
Screen Name, Plate Name, Plate ID, Well, Image ID
INCell Tests, 154, 5, L18969
INCell Tests, 154, 4, I18960
INCell Tests, 154, 3, H18951
INCell Tests, 154, 3, G18942
INCell Tests, 154, 3, E18933
INCell Tests, 154, 3, K18924
INCell Tests, 154, 4, F18915
INCell Tests, 154, 3, A18906
INCell Tests, 154, 2, D18897
jc168@clarinet001-054:~/Checkout/OMERO_scripts$

**Comment by ghost** [comment]
I noticed too that Plate Name shows up twice in the header row when no options are used.

**Comment by dpwrussell** [comment]
The way that `head` works is that it shuts down stdout, then Python throws an exception because it can no longer write to it. So you will often see an error if you do `python foo.py | head`. Easiest way around this is to do `python foo.py | cat | head` so that cat eats the whole output before head is applied.

Nevertheless, there was a bug with regard to the well calculation for `--nonames`, which I have fixed. This was the alphanumeric, wrongly calculating the well from the wrong columns.

**Comment by ghost** [comment]
Finally got a chance to test this. -n option works nicely.

**Pull request merged**
